### ISSUE TITLE
BUG: Cannot read tags in flutter release mode

### ISSUE THREAD

**Issue by rohansohonee** [Samurai016/Audiotagger#1]
``` console
W System.err: java.lang.IllegalArgumentException: NoSuchMethodException: 
Error finding constructor to create copy:
```
``` java
AudioFile audioFile = AudioFileIO.read(file);  // cannot read audio file in release mode
```

The above exception occurs only in flutter release mode.
JAudioTagger library is causing this issue. Can you fix this bug???

**Comment by rohansohonee** [comment]
ID3Tags.java line 323
``` java
throw new IllegalArgumentException("NoSuchMethodException: Error finding constructor to create copy:"+copyObject.getClass().getName());
```
This exception is only thrown in release mode.

**Comment by Samurai016** [comment]
Hi, can you send me your snippet of code? I can't reproduce the error in my code

**Comment by mlican** [comment]
I have the same problem. The release mode compiled by flutter 1.12.13 can't read the tags.

**Comment by mrdong916** [comment]
I have the same problem. The release mode compiled by flutter v1.14.1 can't read the tags.

**Comment by mrdong916** [comment]
这个是由于flutter默认开启了混淆代码导致的，只需要在混淆配置`proguard-rules.pro`文件中排除掉 `org.jaudiotagger`

```
-keep class org.jaudiotagger.**  { *; }
```

**Comment by rohansohonee** [comment]
@mrdong916 solution works. Closing this issue.

**Comment by Samurai016** [comment]
Thank you @mrdong916 , I will update the library as soon as possible. 
Unfortunately in these days I was full of work and I was not able to search the bug.
I really appreciate what you've done.
