### ISSUE TITLE
Update Package to Major Version for support Null Safety

### ISSUE THREAD

**Issue by zgramming** [Samurai016/Audiotagger#11]
As written [here](https://dart.dev/null-safety/migration-guide)
```
If your package is already at 1.0.0 or greater, increase the major version. For example, if the previous version is 2.3.2, the new version is 3.0.0.
```

If you running in terminal `flutter pub outdated --mode=null-safety` used **audiotagger: ^1.1.0** , it still indicates this package not yet support null safety

```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies:
audiotagger   ✗1.1.0   ✗1.1.0      ✗1.1.0      ✗1.1.0
```

# How to fixed it 

Update package version to **2.0.0**

**Comment by Samurai016** [comment]
Thank you so much @zgramming ,
I updated the package and migrated the whole project to support Null-Safety.
I just released the [2.0.0](https://github.com/Samurai016/Audiotagger/releases/tag/2.0.0) version on [pub.dev](https://pub.dev/packages/audiotagger/admin).
