### ISSUE TITLE
Support for IOS

### ISSUE THREAD

**Issue by mohammadne** [Samurai016/Audiotagger#13]
none()

**Comment by Samurai016** [comment]
The problem with iOS is that I'm unable to efficiently test, run and develop iOS code on Windows and I don't have a MacOS PC. I'm waiting for my new PC that maybe will allow me to run a high-performance virtual machine and then allow me to develop iOS code.

**Comment by Samurai016** [comment]
Replied in #16

**Comment by swarupbhc** [comment]
@Samurai016 if you still having the macos issue, I can share my macos daily one hour using anydesk to test your native code
