### ISSUE TITLE
Add length/duration to tags

### ISSUE THREAD

**Issue by moritz-weber** [Samurai016/Audiotagger#14]
It would be great to have the length/duration of songs included in the tags. I know that there is the TLEN frame in ID3 tags and there seems to be some functionality in jaudiotagger. I don't know how much effort it would be to add that to this package though.

**Comment by moritz-weber** [comment]
Ok, so I wasn't actually patient enough to wait for a response and had a look in the code ;)
The length can be retrieved from the AudioHeader of a file.

I added 3 lines (with import) to AudiotaggerPlugin.java:

    import org.jaudiotagger.audio.AudioHeader;
    ...
    // line 200, formerly 199
    AudioHeader audioHeader = audioFile.getAudioHeader();
    ...
    map.put("length", Integer.toString(audioHeader.getTrackLength()));

getPreciseTrackLength would be an alternative that returns the length as double instead of int.
If you like, I can create a pull request for this change.

**Comment by Samurai016** [comment]
Thank you @moritz-weber, 
I read the issue this morning, your idea is great and I think that a better solution could be to implement a Dart class to handle the file audio.
This class would contains the parameters supplied by the [`AudioHeader`](http://www.jthink.net/jaudiotagger/javadoc/index.html) class (like the track length, the bitrate, or others useful informations available in jaudiotagger).
Do you think this could be a better solution or is better to add the length (and maybe bitrate) parameter in the current `Tag` class?

**Comment by moritz-weber** [comment]
Hm, good question. You're probably right as the attributes provided by `AudioHeader` are read only and should therefore be separated from the `Tag` attributes.
I think, I'd only add them to the current `Tag` if it was significantly faster than getting them separately.

**Comment by Samurai016** [comment]
I think I will create a new class to be consistent with the data, I think is non appropriate to mix ID3 informations (like author and title) and technical informations (like track length and bit rate).
Tomorrow I'll work on it, thank you!

**Comment by Samurai016** [comment]
As I told you yesterday I added the `AudioFile` class with the [`AudioHeader`](http://www.jthink.net/jaudiotagger/javadoc/org/jaudiotagger/audio/AudioHeader.html) provided parameters.
I updated the package and I just released the [2.1.0](https://github.com/Samurai016/Audiotagger/releases/tag/2.2.0) version on [pub.dev](https://pub.dev/packages/audiotagger).
You can find the documentation to use the new `readAudioFile` and `readAudioFileAsMap` methods in the [README](https://github.com/Samurai016/Audiotagger#read-audio-file-as-audiofile-object)
