### ISSUE TITLE
Support for Character Encoding - GB18030

### ISSUE THREAD

**Issue by mlican** [Samurai016/Audiotagger#15]

**Comment by Samurai016** [comment]
Are you sure that actually it not support it?
GB18030 is supported in UTF-8 as you can see on [Wikipedia](https://en.wikipedia.org/wiki/GB_18030#Encoding) and Java String by default are encoded in UTF-16 (see [here](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html), second-last paragraph of the top description).
I made a test by providing a GB18030 title to Audiotagger and trying writing them.
As you can see in this screenshot everything gone well.

![Screenshot_1619033938](https://user-images.githubusercontent.com/28674431/115611705-b7862180-a2ea-11eb-84ab-e198e20ccb6b.png)

**Comment by mlican** [comment]
This is my test file

[孙燕姿-开始懂了.mp3](https://github.com/mlican/mymusic/blob/master/%E5%AD%99%E7%87%95%E5%A7%BF-%E5%BC%80%E5%A7%8B%E6%87%82%E4%BA%86.mp3)

Audio tag screenshot

![Screenshot_2021-04-22-11-59-43-290_com sisi music](https://user-images.githubusercontent.com/10806361/115655235-73843280-a365-11eb-9323-3fe058a3501c.jpg)

Audio tags read by Apple Music

![14591619065418_ pic](https://user-images.githubusercontent.com/10806361/115655403-d675c980-a365-11eb-9883-b52d410fcdf8.jpg)

**Comment by Samurai016** [comment]
I updated the package and I just released the [2.2.1](https://github.com/Samurai016/Audiotagger/releases/tag/2.2.1) version on [pub.dev](https://pub.dev/packages/audiotagger).
I changed the encoding type for ID3v1 Tags from `ISO/IEC 8859-1` (used by JAudiotagger library) to `UTF-16`.
I also added a new system that automatically convert ID3v1 to ID3v2.3 so you can also write and read artworks on files that have ID3v1 tags (ID3v1 tags not supports artwork). This new system should also nullify the changing to `UTF-16`.
I hope this could help you, sorry for the delay @mlican🖖.
