### ISSUE TITLE
not able to write tag

### ISSUE THREAD

**Issue by bohrasankalp** [Samurai016/Audiotagger#6]
I am not able to write tags as mentioned. Getting `true` response, if I call write operation but tags are not written. No exception at all. 

Replication: write tags with desired filepath, read again with reading method. no changes

**Comment by bohrasankalp** [comment]
I came across to main points.

1. I can't reset it empty. In case if I wish to clean the single tag and set empty or null it won't work. (that's what I found while debugging). Every time I need to put some text to make it change.
2. Will it work for a single tag(title, artist, album) anyone at the time. Means, suppose case I wish to change artist/title Can I perform a specific operation to write? or I would be like reading tags first and replace values which needs to be change then make write operation.

**Comment by Samurai016** [comment]
Hi @bohrasankalp, I will work on it in the next days, thank you

**Comment by Samurai016** [comment]
Hi @bohrasankalp 
I just updated the library.
I solved the problem that prevented you from resetting the fields, it was a wrong if statement. Now you can reset the fields by pass an empty string `""` as value to the writing methods.

For your second question about the specific operations.
Specific operations were already possible in the old version, it was enough to provide only the desired fields as parameters (even just one).
But now to simplify the process, I created the [`writeTag`](https://github.com/Samurai016/Audiotagger#write-single-tag-field) method to write one field at a time.

I hope this update (1.1.0) will help you.
Sorry for the waiting.
Nicolò

[Link to pub.dev audiotagger page](https://pub.dev/packages/audiotagger)
